<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
	'Actions'                                                              => 'Акции',
	'Activators'                                                           => 'Активаторы',
	'Approve'                                                              => 'Одобрить',
	'Approved users'                                                       => 'Одобренные пользователи',
	'Blocked'                                                              => 'Заблокирована',
	'Cant change status due errors'                                        => 'Невозможно сменить статус из-за ошибок',
	'Decline'                                                              => 'Отклонить',
	'Declined users'                                                       => 'Отклоненные юзеры',
	'Description'                                                          => 'Описание',
	'Group users'                                                          => 'Пользователи группы',
	'Groups'                                                               => 'Группы',
	'Hided'                                                                => 'Скрыта',
	'New users'                                                            => 'Новые пользователи',
	'Not blocked'                                                          => 'Не заблокирована',
	'Not hided'                                                            => 'Не скрыта',
	'Posts'                                                                => 'Записи',
	'Problems'                                                             => 'Проблемы',
	'Status changed successfully'                                          => 'Статус изменен успешно',
	'Users'                                                                => 'Пользователи',
	'Вы не состоите в этой группе'                                         => '',
	'Вы уже состоите в этой группе.'                                       => '',
	'Вы успешно вступили в группу'                                         => '',
	'Группа отредактирована успешно'                                       => '',
	'Группа создана успешно'                                               => '',
	'Группа успешно создана'                                               => '',
	'Закрытая группа'                                                      => '',
	'Изменить блокировку?'                                                 => '',
	'Изменить статус?'                                                     => '',
	'Нельзя изменить статус владельца группы'                              => '',
	'Открытая группа'                                                      => '',
	'При встпулении в группу возникли ошибки'                              => '',
	'При создании группы возникли проблемы, пожалуйста, попробуйте позже.' => '',
	'При сохранении группы возникли ошибки'                                => '',
	'Просмотр групп'                                                       => '',
	'Просмотр группы "{groupName}"'                                        => '',
	'Редактирование группы'                                                => '',
	'Создание группы'                                                      => '',
	'Создать группу'                                                       => '',
	'Управление группами'                                                  => '',
	'Участники группы "{title}"'                                           => '',
);
