<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cant send mail' => '',
  'Cost parameter must be between 4 and 31.' => '',
  'Email not found in database' => '',
  'Email адрес' => '',
  'Incorrect email or password.' => 'Неверный email адрес или пароль',
  'Incorrect password.' => 'Неверный пароль',
  'Login' => 'Вход',
  'Login successful' => 'Вход выполнен',
  'Logout ({user})' => 'Выход ({user})',
  'Logout successful' => 'Выход выполнен',
  'Register' => 'Регистрация',
  'Register successful' => 'Регистрация выполнена',
  'Reset successful' => 'Сброс пароя выполнен',
  'Restore successful' => 'Восстановление пароля выполнено',
  'User not found' => 'Пользователь не найден',
  'Восстановление пароля' => '',
  'Восстановление пароля на сайте {siteName}' => '',
  'Вход' => '',
  'Да' => '',
  'Нет' => '',
  'Новый пароль на сайте {siteName}' => '',
  'Пароль' => '',
  'Регистрация' => '',
  'Регистрация на сайте {siteName}' => '',
  'Сброс пароля' => '',
  'ФИО' => '',
);
