<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Today' => 'Сегодня',
  'Yesterday' => 'Вчера',
  'on {date}' => 'в {date}',
  '{date} ago' => '{date} назад',
  '{n} day|{n} days' => '{n} день|{n} дня|{n} дней',
  '{n} hour|{n} hours' => '{n} час|{n} часа|{n} часов',
  '{n} minute|{n} minutes' => '{n} минуту|{n} минуты|{n} минут',
  '{n} month|{n} months' => '{n} месяц|{n} месяца|{n} месяцев',
  '{n} second|{n} seconds' => '{n} секунду|{n} секунды|{n} секунд',
  '{n} week|{n} weeks' => '{n} неделю|{n} недели|{n} недель',
  '{n} year|{n} years' => '{n} год|{n} года|{n} лет',
);
