<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
	'ID'                                       => '',
	'Атрибуты'                                 => '',
	'Атрибуты категории'                       => '',
	'Атрибуты сохранены успешно'               => '',
	'Атрибуты удалены успешно'                 => '',
	'Валидатор'                                => '',
	'Возникли ошибки при сохранении атрибутов' => '',
	'Возникли ошибки при удалении атрибутов'   => '',
	'Выпадающий список'                        => '',
	'Доступные атрибуты'                       => '',
	'Ед. измерения'                            => '',
	'Название'                                 => '',
	'Обязательное'                             => '',
	'Радио'                                    => '',
	'Радио Да/Нет'                             => '',
	'Редактирование аттрибута'                 => '',
	'Создание аттрибута'                       => '',
	'Сохранить'                                => '',
	'Текстовое поле'                           => '',
	'Тип'                                      => '',
	'Удаление аттрибута'                       => '',
	'Управление атрибутами'                    => '',
	'Управление аттрибутами'                   => '',
	'Чекбокс'                                  => '',
	'category management'                                => 'Управление категориями',
	'categoryattributes' => 'Атрибуты категорий',
);
